### ISSUE TITLE
Add Black pre-commit

### ISSUE THREAD

**Issue by kajuberdut** [pysprings/Pysprings_Badging_System#17]
https://pre-commit.com
https://github.com/ambv/black

This would in theory run black on anything that is being checked in, which has several advantages:
"Black makes code review faster by producing the smallest diffs possible."

It also completely ends the Tab/Space discussion or ' vs ".

Note that for safety black checks that the .pyc file is no different after running black.

**Comment by kajuberdut** [comment]
@mtthedragon01 @ryanfreckleton @rfdoell @mtik00 
Curious in your opinions on this one.

**Comment by mtik00** [comment]
Why don't we just have Travis do it instead of another dependency?

**Comment by kajuberdut** [comment]
It's a great idea @mtik00  and I'll look into it. I don't think it's comparable because the changes need to be checked in and I don't think travis does that.

**Comment by mtik00** [comment]
Travis would check the Pull Request and reject it if anything fails.  It would be commited, but we wouldn't be able to merge it (once CI is implemented, obv).

*shrugs* See what you find out.  I'm fine either way.

**Comment by mtik00** [comment]
FYI, `black` was added to Travis in #24

**Comment by mtik00** [comment]
I actually added `pre-commit` w/ Black to one of my projects, and I :heart_eyes: it.
